# Generated by Django 4.1.7 on 2023-04-01 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Accounts', '0001_initial'),
        ('Works', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='saved',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Works.product'),
        ),
    ]
